services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - debezium-net
    environment:
      CLUSTER_ID: A0JScUJkRzVhM1Z4YTRibA
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    volumes:
      - pgdata_debezium:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    command: [ "postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=4" ]
    networks:
      - debezium-net

  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: debezium
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    networks:
      - debezium-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 10s
      timeout: 5s
      retries: 5

  debezium-init:
    image: curlimages/curl:latest
    container_name: debezium-init
    depends_on:
      debezium:
        condition: service_healthy
    entrypoint: >
      sh -c "
      echo 'Waiting for Debezium to start...';
      sleep 10;
      curl -X POST http://debezium:8083/connectors -H 'Content-Type: application/json' -d '{
        \"name\": \"postgres-products-connector\",
        \"config\": {
          \"connector.class\": \"io.debezium.connector.postgresql.PostgresConnector\",
          \"database.hostname\": \"postgres\",
          \"database.port\": \"5432\",
          \"database.user\": \"admin\",
          \"database.password\": \"password\",
          \"database.dbname\": \"inventory\",
          \"database.server.name\": \"pgdemo\",
          \"plugin.name\": \"pgoutput\",
          \"table.include.list\": \"public.products\",
          \"slot.name\": \"products_slot\",
          \"topic.prefix\": \"pgdemo\",
          \"snapshot.mode\": \"initial\"
        }
      }';
      echo 'Debezium connector registered!'
      "
    networks:
      - debezium-net

  consumer:
    build:
      context: ./src/KafkaDebeziumConsumer
    container_name: consumer
    depends_on:
      debezium-init:
        condition: service_completed_successfully
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - debezium-net

volumes:
  kafka-data:
  pgdata_debezium:

networks:
  debezium-net:
    driver: bridge
